#!/bin/bash
# Squid HTTPS Proxy Installer with Cloudflare ACME & Auth Management
# Usage: sudo bash install_squid_proxy.sh

# Check root privileges
if [ "$(id -u)" != "0" ]; then
    echo "This script must be run as root. Use: sudo bash $0"
    exit 1
fi

# Install required dependencies
echo "Updating package list and installing dependencies..."
apt update -y
apt install -y squid certbot certbot-dns-cloudflare curl jq

# Interactive configuration
echo "===== Squid HTTPS Proxy Installation ====="
echo "Please provide the following information:"

# Domain input
read -p "1. Enter your domain (e.g. proxy.example.com): " DOMAIN
while [ -z "$DOMAIN" ]; do
    read -p "Domain cannot be empty. Enter your domain: " DOMAIN
done

# Cloudflare API Token
echo -e "\n2. Cloudflare API Token (must have Zone:Edit permission)"
echo "   - Get it from: https://dash.cloudflare.com/profile/api-tokens"
read -s -p "   API Token: " CLOUDFLARE_TOKEN
echo -e "\n"

# Email for Let's Encrypt
read -p "3. Enter your email for Let's Encrypt (used for certificate notifications): " EMAIL
while [ -z "$EMAIL" ]; do
    read -p "Email cannot be empty. Enter your email: " EMAIL
done

# Proxy credentials
echo -e "\n4. Set up proxy authentication"
read -p "   Username: " USERNAME
while [ -z "$USERNAME" ]; do
    read -p "Username cannot be empty. Enter username: " USERNAME
done

read -s -p "   Password (will not be shown): " PASSWORD
echo -e "\n"
read -s -p "   Confirm Password: " CONFIRM_PASSWORD
echo -e "\n"

if [ "$PASSWORD" != "$CONFIRM_PASSWORD" ]; then
    echo "Error: Passwords do not match. Exiting."
    exit 1
fi

# Get Cloudflare Zone ID
echo -e "\nFetching Cloudflare Zone ID for $DOMAIN..."
ZONE_ID=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones?name=$DOMAIN" \
    -H "Authorization: Bearer $CLOUDFLARE_TOKEN" \
    -H "Content-Type: application/json" | jq -r '.result[0].id')

if [ -z "$ZONE_ID" ] || [ "$ZONE_ID" = "null" ]; then
    echo "Error: Zone ID not found for $DOMAIN. Check your domain and API token permissions."
    echo "Make sure your API token has Zone:Edit permission and the domain exists in Cloudflare."
    exit 1
fi

# Generate Cloudflare credentials file
echo "dns_cloudflare_api_token = $CLOUDFLARE_TOKEN" > /etc/cloudflare/credentials.ini
mkdir -p /etc/cloudflare
chmod 600 /etc/cloudflare/credentials.ini

# Request Let's Encrypt certificate
echo -e "\nRequesting SSL certificate from Let's Encrypt..."
CERT_RETRY=0
while [ $CERT_RETRY -lt 3 ]; do
    if certbot certonly --dns-cloudflare --dns-cloudflare-credentials /etc/cloudflare/credentials.ini \
        --dns-cloudflare-propagation-seconds 30 \
        -d "$DOMAIN" \
        --email "$EMAIL" \
        --agree-tos \
        --non-interactive \
        --quiet; then
        break
    else
        CERT_RETRY=$((CERT_RETRY + 1))
        echo "Certificate request failed. Retrying ($CERT_RETRY/3)..."
        sleep 2
    fi
done

if [ ! -f "/etc/letsencrypt/live/$DOMAIN/fullchain.pem" ]; then
    echo "Error: Certificate request failed after 3 attempts. Exiting."
    exit 1
fi

# Configure Squid
echo -e "\nConfiguring Squid proxy..."
SQUID_CONF="/etc/squid/squid.conf"
cp "$SQUID_CONF" "${SQUID_CONF}.bak"

# Backup original config
echo "Backup created at $SQUID_CONF.bak"

# Replace configuration with our settings
cat > "$SQUID_CONF" << EOF
# Squid HTTPS Proxy Configuration (Generated by install_squid_proxy.sh)
acl SSL_ports port 443
acl Safe_ports port 80,443
acl CONNECT method CONNECT

http_port 443 ssl-bump cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem key=/etc/letsencrypt/live/$DOMAIN/privkey.pem
https_port 443 ssl-bump cert=/etc/letsencrypt/live/$DOMAIN/fullchain.pem key=/etc/letsencrypt/live/$DOMAIN/privkey.pem

# Proxy authentication
auth_param basic program /usr/lib/squid/basic_ncsa_auth /etc/squid/passwd
auth_param basic children 5
auth_param basic realm Squid Proxy
auth_param basic credentialsttl 2 hours
acl authenticated_users proxy_auth REQUIRED
http_access allow authenticated_users
http_access deny all

# Allow all traffic
http_access allow all
cache_mgr admin@$DOMAIN
cache_effective_user squid
cache_effective_group squid
EOF

# Create proxy password file
echo -e "\nSetting up proxy authentication..."
echo "$USERNAME:$PASSWORD" > /etc/squid/passwd
chmod 640 /etc/squid/passwd
chown root:squid /etc/squid/passwd

# Enable SSL bumping
echo "ssl_bump server-first all" >> "$SQUID_CONF"

# Restart Squid
systemctl restart squid
systemctl enable squid

# Create management command
echo -e "\nCreating management command 'proxy'..."
cat > /usr/local/bin/proxy << EOF
#!/bin/bash
# Proxy Management Command

case "\$1" in
    install)
        echo "Squid proxy is already installed. Use 'proxy config' to reconfigure."
        ;;
    uninstall)
        echo "Uninstalling Squid proxy..."
        systemctl stop squid
        systemctl disable squid
        rm -f /etc/squid/squid.conf /etc/squid/passwd /etc/cloudflare/credentials.ini
        apt remove -y squid certbot certbot-dns-cloudflare
        rm -f /usr/local/bin/proxy
        echo "Squid proxy uninstalled successfully."
        ;;
    config)
        echo "Reconfiguring Squid proxy..."
        /etc/squid/squid.conf.bak > /etc/squid/squid.conf
        /usr/local/bin/proxy change-pass
        systemctl restart squid
        echo "Configuration updated. Proxy restarted."
        ;;
    change-pass)
        read -p "Enter new username: " NEW_USER
        read -s -p "Enter new password: " NEW_PASS
        echo -e "\n"
        read -s -p "Confirm new password: " CONFIRM_PASS
        echo -e "\n"
        if [ "$NEW_PASS" != "$CONFIRM_PASS" ]; then
            echo "Error: Passwords do not match."
            exit 1
        fi
        echo "\$NEW_USER:\$NEW_PASS" > /etc/squid/passwd
        chmod 640 /etc/squid/passwd
        chown root:squid /etc/squid/passwd
        systemctl restart squid
        echo "Password changed successfully."
        ;;
    restart)
        systemctl restart squid
        echo "Squid restarted."
        ;;
    *)
        echo "Usage: proxy [install|uninstall|config|change-pass|restart]"
        echo "  install: Install Squid (already installed)"
        echo "  uninstall: Remove Squid and all configurations"
        echo "  config: Reconfigure proxy settings"
        echo "  change-pass: Change proxy authentication password"
        echo "  restart: Restart Squid service"
        ;;
esac
EOF

chmod +x /usr/local/bin/proxy
echo "Management command 'proxy' created at /usr/local/bin/proxy"

# Final setup message
echo -e "\n===== Installation Complete ====="
echo "Squid HTTPS Proxy is now running on port 443."
echo "Proxy URL: https://$DOMAIN"
echo "Authentication: $USERNAME / $PASSWORD (will be changed immediately)"

# Force password change prompt
echo -e "\n\033[1;31mIMPORTANT: You MUST change the default password immediately!\033[0m"
echo "Run: proxy change-pass"
echo "Do NOT close this terminal until you change the password."

# Keep terminal open for password change
read -p "Press Enter to exit (after changing password with 'proxy change-pass')..." dummy
